### ISSUE TITLE
EnderIO Crash

### ISSUE THREAD

**Issue by mitchej123** [GTNewHorizons/Angelica#154]
### Mod Version

1.0.0-alpha13-pre

### Java Version

Java 17

### Bug Report

```
java.lang.RuntimeException: Chunk build failed
    at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.handleFailures(ChunkBuilder.java:219)
    at me.jellysquid.mods.sodium.client.render.chunk.ChunkRenderManager.updateChunks(ChunkRenderManager.java:584)
    at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:237)
    at net.minecraft.client.renderer.RenderGlobal.clipRenderersByFrustum(RenderGlobal.java:5180)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1181)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1015)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.run(Minecraft.java:4110)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:568)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:165)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
    at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
    at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
    at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "crazypants.enderio.conduit.IConduitBundle.hasFacade()" because "bundle" is null
    at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:206)
    at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:409)
    at java.lang.Thread.run(Thread.java:833)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "crazypants.enderio.conduit.IConduitBundle.hasFacade()" because "bundle" is null
    at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
    at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
    at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:201)
    ... 2 more
Caused by: java.lang.NullPointerException: Cannot invoke "crazypants.enderio.conduit.IConduitBundle.hasFacade()" because "bundle" is null
    at crazypants.enderio.conduit.render.ConduitBundleRenderer.renderFacade(ConduitBundleRenderer.java:147)
    at crazypants.enderio.conduit.render.ConduitBundleRenderer.renderWorldBlock(ConduitBundleRenderer.java:125)
    at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
    at FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
    at net.minecraft.client.renderer.RenderBlocks.renderBlockByRenderType(RenderBlocks.java:296)
    at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderModel(BlockRenderer.java:63)
    at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performMainBuild(ChunkRenderRebuildTask.java:270)
    at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.lambda$performBuild$0(ChunkRenderRebuildTask.java:201)
    at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
    at com.gtnewhorizons.angelica.rendering.AngelicaRenderQueue.processTasks(AngelicaRenderQueue.java:33)
    at net.minecraft.client.renderer.RenderGlobal.updateRenderers(RenderGlobal.java:5101)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1187)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1015)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.run(Minecraft.java:4110)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:568)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:165)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
    at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
    at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
    at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

```

### Mod List or GTNH Pack Version

NH 2.5.1 + angelica + amazing trophies

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by MarshTheBacca** [comment]
I had a similar crash when shift-right-click-wrenching an item conduit on a more recent Angelica version:
https://mclo.gs/eT2hDjJ

Environment:
Java21

GTNH 2.5.1
+Angelica 1.0.0-alpha36
+lwjgl3ify 1.5.7
+Hodgepodge 2.4.40
+CodeChickenCore 1.2.1
+CodeChickenLib 1.2.1
+GTNHLib 0.2.11

Crash scene:
![2024-04-22_02 57 30](https://github.com/GTNewHorizons/Angelica/assets/34864792/f7ef417d-4df7-4f3d-a594-dbc2bdfe1110)

Upon re-logging, the crash did not reoccur.
