### ISSUE TITLE
Crash when loadinging chunks[Explore the map] in middleearth [lotr mod]

### ISSUE THREAD

**Issue by wangyu2333333** [GTNewHorizons/Angelica#276]
### Mod Version

alpha 24

### Java Version

Java 8

### Bug Report

Description: Unexpected error

java.lang.RuntimeException: Chunk build failed
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.handleFailures(ChunkBuilder.java:219)
	at me.jellysquid.mods.sodium.client.render.chunk.ChunkRenderManager.updateChunks(ChunkRenderManager.java:584)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:237)
	at net.minecraft.client.renderer.RenderGlobal.func_72729_a(RenderGlobal.java:5680)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1181)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:6006)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at oolloo.jlw.Wrapper.main(Wrapper.java:53)
Caused by: java.lang.RuntimeException: No result was produced by the task
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:426)
	at java.lang.Thread.run(Thread.java:750)

### Mod List or GTNH Pack Version

	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	xaeroworldmap_core{1.7.10-1.0} [XaeroWorldMapCore] (minecraft.jar) 
	UCHIJA	xaerominimap_core{1.7.10-1.0} [XaeroMinimapCore] (minecraft.jar) 
	UCHIJA	CodeChickenCore{1.2.1} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	InputFix{1.7.10-v5} [InputFix] (minecraft.jar) 
	UCHIJA	NotEnoughItems{2.5.14-GTNH-pre} [NotEnoughItems] (NotEnoughItems-2.5.14-GTNH-pre.jar) 
	UCHIJA	redirectionor{1.7.10} [Redirectionor] (minecraft.jar) 
	UCHIJA	smoothfontcore{1.7.10-1.15.1} [Smooth Font Core] (minecraft.jar) 
	UCHIJA	FoamFixCore{1.0.4} [FoamFixCore] (minecraft.jar) 
	UCHIJA	smoothfont{1.7.10-1.15.3} [Smooth Font] (SmoothFont-1.7.10-1.15.3.jar) 
	UCHIJA	gravestone{0.7.10.3} [Gravestone] ([墓碑]GraveStone.jar) 
	UCHIJA	NBTEdit{1.7.2.2} [In-game NBTEdit] ([物品编辑]NBTEdit_1.7.10.jar) 
	UCHIJA	customnpcs{1.8.6} [CustomNPC+] (CustomNPC-Plus-1.8.6-nomixin.jar) 
	UCHIJA	lotr{Update v1.3.1} [LOTR Mod Reworked] (LOTRReworked-1.3.1无魔改版.jar) 
	UCHIJA	TwilightForest{2.4.3} [The Twilight Forest] (TwilightForest-2.4.3.jar) 
	UCHIJA	unimixins{0.1.15} [UniMixins] (+unimixins-all-1.7.10-0.1.15.jar) 
	UCHIJA	unimixins-mixin{0.1.15} [UniMixins: Mixin (UniMix)] (+unimixins-all-1.7.10-0.1.15.jar) 
	UCHIJA	unimixins-compat{0.1.15} [UniMixins: Compatibility] (+unimixins-all-1.7.10-0.1.15.jar) 
	UCHIJA	mixingasm{0.3} [UniMixins: Mixingasm] (+unimixins-all-1.7.10-0.1.15.jar) 
	UCHIJA	spongemixins{2.0.1} [UniMixins: SpongeMixins] (+unimixins-all-1.7.10-0.1.15.jar) 
	UCHIJA	mixinbooterlegacy{1.2.1} [UniMixins: MixinBooterLegacy] (+unimixins-all-1.7.10-0.1.15.jar) 
	UCHIJA	gasstation{0.5.1} [UniMixins: GasStation] (+unimixins-all-1.7.10-0.1.15.jar) 
	UCHIJA	gtnhmixins{2.2.0} [UniMixins: GTNHMixins] (+unimixins-all-1.7.10-0.1.15.jar) 
	UCHIJA	mixinextras{0.1.15} [UniMixins: MixinExtras] (+unimixins-all-1.7.10-0.1.15.jar) 
	UCHIJA	XaeroWorldMap{1.14.1.31} [Xaero's World Map] ([Xaeros世界地图]XaerosWorldMap_1.14.1.31_Forge_1.7.10.jar) 
	UCHIJA	XaeroMinimap{21.10.41} [Xaero's Minimap] ([Xaeros小地图]Xaeros_Minimap_21.10.41_Forge_1.7.10.jar) 
	UCHIJA	replaymod-restrictions{1.7.10-2.5.2} [Replay Mod - Restrictions] ([录像回放]replaymod-1.7.10-2.5.2.jar) 
	UCHIJA	replaymod{1.7.10-2.5.2} [Replay Mod] ([录像回放]replaymod-1.7.10-2.5.2.jar) 
	UCHIJA	lotrclient{1.2.9} [?6LOTR Client] ([快速重生]LOTR Client.jar) 
	UCHIJA	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] ([血条]Neat 1.0-1.jar) 
	UCHIJA	mcpatcherforge{1.0.0-alpha} [MCPatcherForge] (angelica-1.0.0-alpha24.jar) 
	UCHIJA	notfine{1.0.0-alpha24} [NotFine] (angelica-1.0.0-alpha24.jar) 
	UCHIJA	gtnhlib{0.2.3} [GTNH Lib] (gtnhlib-0.2.3.jar) 
	UCHIJA	angelica{1.0.0-alpha24} [Angelica] (angelica-1.0.0-alpha24.jar) 
	UCHIJA	embeddium{1.0.0-alpha24} [Embeddium] (angelica-1.0.0-alpha24.jar) 
	UCHIJA	AppleCore{3.2.12} [AppleCore] (AppleCore-3.2.12.jar) 
	UCHIJA	hud{1.3.5} [Better HUD] (Better+HUD+by+NukeDuck+[1.7.10][1.3.5].jar) 
	UCHIJA	bugtorch{1.2.11} [BugTorch] (bugtorch-1.2.11.jar) 
	UCHIJA	coretweaks{0.3.3.2} [CoreTweaks] (CoreTweaks-1.7.10-0.3.3.2+nomixin.jar) 
	UCHIJA	DynamicLights{1.3.9a} [Dynamic Lights] (Dynamic+Lights-1.3.9a-MC1.7.10.jar) 
	UCHIJA	foamfix{@VERSION@} [FoamFix] (FoamFix-1.7.10-universal-1.0.4.jar) 
	UCHIJA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJA	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks-2.4.4-mc1.7.10.jar) 
	UCHIJA	neirecipehandlers{1.1.0-BETA} [NEI Recipe Handlers] (neiRecipeHandlers-1.1.0-BETA.jar) 
	UCHIJA	vlzoomer{1.0.0} [VeryLegacyZoomer] (VeryLegacyZoomer-Forge-1.7.10-1.0.0.jar) 

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not shader related  (they aren't ready yet for testing)

**Comment by mist475** [comment]
Does the issue persist with regular lotr? We only support the official release of lotr

**Comment by wangyu2333333** [comment]
> 常规 lotr 是否仍然存在问题？我们只支持 lotr 的官方发布

yes,and this problem is usually in the oceanic biome
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.handleFailures(ChunkBuilder.java:219)
	at me.jellysquid.mods.sodium.client.render.chunk.ChunkRenderManager.updateChunks(ChunkRenderManager.java:584)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:237)
	at net.minecraft.client.renderer.RenderGlobal.func_72729_a(RenderGlobal.java:3180)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1181)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at oolloo.jlw.Wrapper.main(Wrapper.java:53)
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	lotr{Update v36.15 for Minecraft 1.7.10} [The Lord of the Rings Mod] (LOTRMod+v36.15 chs.jar) 
	UCHIJA	unimixins{0.1.15} [UniMixins] (+unimixins-all-1.7.10-0.1.15.jar) 
	UCHIJA	unimixins-mixin{0.1.15} [UniMixins: Mixin (UniMix)] (+unimixins-all-1.7.10-0.1.15.jar) 
	UCHIJA	unimixins-compat{0.1.15} [UniMixins: Compatibility] (+unimixins-all-1.7.10-0.1.15.jar) 
	UCHIJA	mixingasm{0.3} [UniMixins: Mixingasm] (+unimixins-all-1.7.10-0.1.15.jar) 
	UCHIJA	spongemixins{2.0.1} [UniMixins: SpongeMixins] (+unimixins-all-1.7.10-0.1.15.jar) 
	UCHIJA	mixinbooterlegacy{1.2.1} [UniMixins: MixinBooterLegacy] (+unimixins-all-1.7.10-0.1.15.jar) 
	UCHIJA	gasstation{0.5.1} [UniMixins: GasStation] (+unimixins-all-1.7.10-0.1.15.jar) 
	UCHIJA	gtnhmixins{2.2.0} [UniMixins: GTNHMixins] (+unimixins-all-1.7.10-0.1.15.jar) 
	UCHIJA	mixinextras{0.1.15} [UniMixins: MixinExtras] (+unimixins-all-1.7.10-0.1.15.jar) 
	UCHIJA	notfine{1.0.0-alpha22} [NotFine] (angelica-1.0.0-alpha22.jar) 
	UCHIJA	mcpatcherforge{1.0.0-alpha} [MCPatcherForge] (angelica-1.0.0-alpha22.jar) 
	UCHIJA	gtnhlib{0.2.3} [GTNH Lib] (gtnhlib-0.2.3.jar) 
	UCHIJA	angelica{1.0.0-alpha22} [Angelica] (angelica-1.0.0-alpha22.jar) 
	UCHIJA	embeddium{1.0.0-alpha22} [Embeddium] (angelica-1.0.0-alpha22.jar) 
	UCHIJA	bugtorch{1.2.11} [BugTorch] (bugtorch-1.2.11.jar)

**Comment by PhantomCloak** [comment]
By looking at the stack trace I faced very similar issue when high number of chunks are deleted. In my case I'm when I detonated high yield bombs that came with HBM my game most likely to crash if I'm too close the center, probability gets higher as deleted chunk number increases in my field of view.

**Comment by wangyu2333333** [comment]
yeah,I just explore the map with very high speed，but game crashed

**Comment by PhantomCloak** [comment]
After a bit trivial and error I might be solved the issue on my side. I tried to launch game through Prism launcher with [Zulu-8 Arm64 JDK](https://www.azul.com/downloads/?version=java-8-lts&os=macos&architecture=arm-64-bit&package=jdk#zulu) and I'm no longer able to produce the issue also few bugs about windowing disappeared if you are on the M1 machine could you try to reproduce on your machine with similar setup @wangyu2333333
