### ISSUE TITLE
carpenters are crashing

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/Angelica#317]
### Your GTNH Discord Username

boubou_19

### Mod Version

alpha-28

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

```
java.lang.RuntimeException: Chunk build failed
    at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.handleFailures(ChunkBuilder.java:219)
    at me.jellysquid.mods.sodium.client.render.chunk.ChunkRenderManager.updateChunks(ChunkRenderManager.java:586)
    at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:237)
    at net.minecraft.client.renderer.RenderGlobal.clipRenderersByFrustum(RenderGlobal.java:5180)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1181)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1015)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.run(Minecraft.java:4110)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:165)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
    at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
    at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
    at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.util.IIcon.func_94215_i()" because "icon" is null
    at com.carpentersblocks.renderer.helper.RenderHelper.prepareRender(RenderHelper.java:139)
    at com.carpentersblocks.renderer.helper.RenderHelper$HelperOblWedge.renderSlopeZNeg(RenderHelper.java:1246)
    at com.carpentersblocks.renderer.BlockHandlerCarpentersSlope.renderBaseSide(BlockHandlerCarpentersSlope.java:402)
    at com.carpentersblocks.renderer.BlockHandlerSloped.render(BlockHandlerSloped.java:163)
    at com.carpentersblocks.renderer.BlockHandlerBase.setColorAndRender(BlockHandlerBase.java:657)
    at com.carpentersblocks.renderer.BlockHandlerBase.delegateSideRender(BlockHandlerBase.java:607)
    at com.carpentersblocks.renderer.BlockHandlerSloped.setIDAndRender(BlockHandlerSloped.java:43)
    at com.carpentersblocks.renderer.BlockHandlerCarpentersSlope.prepareHorizontalWedge(BlockHandlerCarpentersSlope.java:1054)
    at com.carpentersblocks.renderer.BlockHandlerCarpentersSlope.renderSlope(BlockHandlerCarpentersSlope.java:531)
    at com.carpentersblocks.renderer.BlockHandlerCarpentersSlope.renderBaseBlock(BlockHandlerCarpentersSlope.java:600)
    at com.carpentersblocks.renderer.BlockHandlerSloped.renderBlock(BlockHandlerSloped.java:180)
    at com.carpentersblocks.renderer.BlockHandlerBase.renderCarpentersBlock(BlockHandlerBase.java:809)
    at com.carpentersblocks.renderer.BlockHandlerBase.renderWorldBlock(BlockHandlerBase.java:129)
    at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
    at FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
    at net.minecraft.client.renderer.RenderBlocks.renderBlockByRenderType(RenderBlocks.java:296)
    at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderModel(BlockRenderer.java:90)
    at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:158)
    at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:409)
    at java.lang.Thread.run(Thread.java:1583)
```

### Mod List or GTNH Pack Version

GTNH 2.5.1 with a few updated mods, in particular with a carpentersblocks' mod jar built from https://github.com/GTNewHorizons/CarpentersBlocks/pull/6

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by mitchej123** [comment]
Should be fixed with alpha29 and latest commit on the carpenter block thread
