### ISSUE TITLE
Conflict with Project Red

### ISSUE THREAD

**Issue by Cyl18** [GTNewHorizons/Angelica#32]
```
	at org.lwjgl.opengl.GL11C.glBindTexture(Native Method)
	at org.lwjgl.opengl.GL11.glBindTexture(GL11.java:854)
	at org.lwjglx.opengl.GL11.glBindTexture(GL11.java:559)
	at com.gtnewhorizons.angelica.glsm.GLStateManager.glBindTexture(GLStateManager.java:399)
	at net.minecraft.client.renderer.texture.TextureUtil.func_94277_a(TextureUtil.java:342)
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:48)
	at codechicken.lib.render.TextureUtils.bindAtlas(TextureUtils.java:100)
	at mrtjp.projectred.transmission.TWireCommons$class.renderStatic(wireabstracts.scala:152)
	at mrtjp.projectred.transmission.WirePart.renderStatic(wireabstracts.scala:191)
	at codechicken.multipart.TileMultipartClient$$anonfun$renderStatic$1.apply(TileMultipart.scala:453)
	at codechicken.multipart.TileMultipartClient$$anonfun$renderStatic$1.apply(TileMultipart.scala:453)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:110)
	at scala.collection.immutable.List.foldLeft(List.scala:83)
	at codechicken.multipart.TileMultipartClient$class.renderStatic(TileMultipart.scala:453)
	at TileMultipart_cmp$$0.renderStatic(Unknown Source)
	at codechicken.multipart.MultipartRenderer$.renderWorldBlock(MultipartRenderer.scala:86)
	at com.gtnewhorizons.angelica.rendering.AngelicaBlockRenderingHandler.renderWorldBlock(AngelicaBlockRenderingHandler.java:41)
	- locked <0x00000006ce59f478> (a java.lang.Class for com.gtnewhorizons.angelica.rendering.AngelicaBlockRenderingHandler)
	at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
	at FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:296)
	at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderModel(BlockRenderer.java:68)
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:134)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:342)
	at java.lang.Thread.run(java.base@17.0.9/Thread.java:842)
```

StackOverrun

**Comment by mitchej123** [comment]
Not ready for use

**Comment by ah-OOG-ah** [comment]
Partially addressed by https://github.com/GTNewHorizons/ProjectRed/pull/27, but there's still a concurrency issue - items and blocks using ForgeMultipart try to access the same static class, causing bad rendering at best and CME/NPEs in Project Red.

**Comment by ah-OOG-ah** [comment]
Completely fixed by https://github.com/GTNewHorizons/Angelica/tree/e812c58d3e5e59086df56281eb4d99ce87419029
