### ISSUE TITLE
Zume mod incompatible: NoClassDefFoundError: net/minecraft/client/renderer/EntityRenderer

### ISSUE THREAD

**Issue by SKProCH** [GTNewHorizons/Angelica#327]
### Your GTNH Discord Username

skproch

### Mod Version

1.0.0-alpha29

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

[Zume mod](https://www.curseforge.com/minecraft/mc-mods/zume) version 0.14.0 produces this error at startup:
```
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/EntityRenderer
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:505)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:5099)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:165)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
    at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
    at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
    at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.EntityRenderer
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:115)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 10 more
```
Full log: https://mclo.gs/1VGDILV

### Mod List or GTNH Pack Version

2.5.1, ArchaicFix, Zume

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Nolij** [comment]
Update UniMixins to 0.1.15 or newer. Zume is not compatible with UniMixins versions older than this.

**Comment by SKProCH** [comment]
Yep, this worked. Thanks, @Nolij!
