### ISSUE TITLE
AE2 compat for angelica isn't working

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/Angelica#339]
### Your GTNH Discord Username

boubou_19

### Mod Version

alpha-28

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

```
java.lang.RuntimeException: Chunk build failed
    at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.handleFailures(ChunkBuilder.java:219)
    at me.jellysquid.mods.sodium.client.render.chunk.ChunkRenderManager.updateChunks(ChunkRenderManager.java:586)
    at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:237)
    at net.minecraft.client.renderer.RenderGlobal.clipRenderersByFrustum(RenderGlobal.java:5680)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1181)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1015)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.run(Minecraft.java:5110)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:165)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
    at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
    at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
    at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.util.IIcon.func_94215_i()" because "icon" is null
    at com.gtnewhorizons.angelica.utils.AnimationsRenderUtils.markBlockTextureForUpdate(AnimationsRenderUtils.java:19)
    at net.minecraft.client.renderer.RenderBlocks.handler$zgh000$angelica$beforeRenderFace(RenderBlocks.java:8862)
    at net.minecraft.client.renderer.RenderBlocks.renderFaceZNeg(RenderBlocks.java)
    at appeng.client.render.RenderBlocksWorkaround.renderFaceZNeg(RenderBlocksWorkaround.java:349)
    at appeng.client.render.BaseBlockRender.renderFace(BaseBlockRender.java:724)
    at appeng.client.render.BusRenderHelper.renderFace(BusRenderHelper.java:585)
    at appeng.parts.networking.PartCable.renderAllFaces(PartCable.java:895)
    at appeng.parts.networking.PartCable.renderSmartConnection(PartCable.java:754)
    at appeng.parts.networking.PartCableSmart.renderStatic(PartCableSmart.java:208)
    at appeng.client.render.CableRenderHelper.renderStatic(CableRenderHelper.java:57)
    at appeng.parts.CableBusContainer.renderStatic(CableBusContainer.java:731)
    at appeng.client.render.blocks.RendererCableBus.renderInWorld(RendererCableBus.java:47)
    at appeng.client.render.blocks.RendererCableBus.renderInWorld(RendererCableBus.java:26)
    at appeng.client.render.WorldRender.renderWorldBlock(WorldRender.java:59)
    at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
    at FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
    at net.minecraft.client.renderer.RenderBlocks.renderBlockByRenderType(RenderBlocks.java:296)
    at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderModel(BlockRenderer.java:90)
    at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:158)
    at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:409)
    at java.lang.Thread.run(Thread.java:1583)
```

### Mod List or GTNH Pack Version

2.5.1 with a bunch of updated mods, in particular a custom built version of the AE2 rv3 beta 292 with this PR:https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/478 made by @Cleptomania 

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Cleptomania** [comment]
Is this fixed as of https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/484?
