### ISSUE TITLE
Crash at end of loading on macOS 14.2.1

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/Angelica#36]
### Your GTNH Discord Username

bombcar

### Mod Version

1.0.0-alpha1

### Java Version

Java 17

### Bug Report

Added required mods, yeeted optifine.

Got `abort() called` and

```
[00:43:59] [Client thread/INFO] [modularui]: Reloading GUIs
FATAL ERROR in native method: Thread[Client thread,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.GL30C.glBindVertexArray(Native Method)
	at org.lwjgl.opengl.GL30.glBindVertexArray(GL30.java:2283)
	at org.lwjglx.opengl.GL30.glBindVertexArray(GL30.java:278)
	at me.jellysquid.mods.sodium.client.gl.state.GlStateTracker.applyRestoreState(GlStateTracker.java:53)
	at me.jellysquid.mods.sodium.client.gl.device.GLRenderDevice.makeInactive(GLRenderDevice.java:53)
	at me.jellysquid.mods.sodium.client.gl.device.RenderDevice.exitManagedCode(RenderDevice.java:13)
	at net.minecraft.client.renderer.RenderGlobal.handler$zdp000$angelica$onReload(RenderGlobal.java:4738)
	at net.minecraft.client.renderer.RenderGlobal.func_72712_a(RenderGlobal.java:4748)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:626)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:327)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3599)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@17.0.9/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@17.0.9/NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.9/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@17.0.9/Method.java:568)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:165)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@17.0.9/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@17.0.9/NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.9/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@17.0.9/Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

### Mod List

https://api.paste.ee/p/2iq7v - full GTNH pack with some minor updates from 2.5.1 from testing.

[probablyuseless.txt](https://github.com/GTNewHorizons/Angelica/files/13764539/probablyuseless.txt)
 - crash report from Apple

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.

**Comment by bombcar** [comment]
(for completeness, happens on j21 also. I blame jobs)

**Comment by The-Minecraft-Scientist** [comment]
Apple's OpenGL drivers are really, really shit. You only get GL2.1 if you want compatibility profile (which GTNH needs because a lot of mods still use the GL1 fixed function stuff). I'm open to working on fixing/debugging this, but it may end up being a driver limitation

**Comment by bombcar** [comment]
Yeah Apple OpenGL is crap but it would be nice to be able to at least cripple along. Mitch has it running on his Mac so it maybe a processor/GPU thing or similar

**Comment by The-Minecraft-Scientist** [comment]
That makes me feel a lot better about working on this, I'll try to repro the crash in a debugger to see what the java call stack looks like

**Comment by mitchej123** [comment]
I ran it on OSX a few weeks ago.  Try disabling the startup screen.

I'll give it another try on my mac laptops in the next few days.

**Comment by mitchej123** [comment]
As a note: OSX only ran the oneshot renderer given we're currently doing OGL 2.3 compat.  Multidraw is 4.6+

The best we could hope for is 3.2core; but that needs some lwjgl3ify changes and mod changes/hax/asm.

**Comment by bombcar** [comment]
Same thing with or without splash.properties enabled=false, and without BLS entirely.

**Comment by mitchej123** [comment]
Hmm, I'll give it another run on my osx laptop in dev, and with the full pack tomorrow and see if I can track it down.

**Comment by bombcar** [comment]
`runclient17` got the same crash

```
FATAL ERROR in native method: Thread[Client thread,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
        at org.lwjgl.opengl.GL30C.glBindVertexArray(Native Method)
        at org.lwjgl.opengl.GL30.glBindVertexArray(GL30.java:2283)
        at org.lwjglx.opengl.GL30.glBindVertexArray(GL30.java:278)
```
