### ISSUE TITLE
Crash on MacOS

### ISSUE THREAD

**Issue by The-Minecraft-Scientist** [GTNewHorizons/Angelica#37]
### Your GTNH Discord Username

rsci.

### Mod Version

1.0.0-alpha1

### Java Version

Java 19

### Bug Report

Angelica crashes just before entering the main menu after loading with a generic error about a bad function call on the openGL context: (feel free to ping/dm me on discord, I'm pretty experienced with java/mc modding and very much willing to help debug this)
```
FATAL ERROR in native method: Thread[#1,Client thread,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.GL30C.glBindVertexArray(Native Method)
	at org.lwjgl.opengl.GL30.glBindVertexArray(GL30.java:2283)
	at org.lwjglx.opengl.GL30.glBindVertexArray(GL30.java:278)
	at me.jellysquid.mods.sodium.client.gl.state.GlStateTracker.applyRestoreState(GlStateTracker.java:53)
	at me.jellysquid.mods.sodium.client.gl.device.GLRenderDevice.makeInactive(GLRenderDevice.java:53)
	at me.jellysquid.mods.sodium.client.gl.device.RenderDevice.exitManagedCode(RenderDevice.java:13)
	at net.minecraft.client.renderer.RenderGlobal.handler$zdp000$angelica$onReload(RenderGlobal.java:4738)
	at net.minecraft.client.renderer.RenderGlobal.func_72712_a(RenderGlobal.java:4748)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:626)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:327)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3599)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at java.lang.invoke.LambdaForm$DMH/0x0000000801003000.invokeStatic(java.base@19.0.2/LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$MH/0x0000000801384800.invoke(java.base@19.0.2/LambdaForm$MH)
	at java.lang.invoke.Invokers$Holder.invokeExact_MT(java.base@19.0.2/Invokers$Holder)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.base@19.0.2/DirectMethodHandleAccessor.java:155)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(java.base@19.0.2/DirectMethodHandleAccessor.java:104)
	at java.lang.reflect.Method.invoke(java.base@19.0.2/Method.java:578)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:165)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
	at java.lang.invoke.LambdaForm$DMH/0x0000000801003400.invokeStaticInit(java.base@19.0.2/LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$MH/0x0000000801003c00.invokeExact_MT(java.base@19.0.2/LambdaForm$MH)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```
notable context:
Apple OpenGL drivers are really shitty and outdated, only allowing up to GL2.1 in compatibility profile. This is (unfortunately) most likely the root cause of this issue
macos version: 12.4
rx 6800
(intel mac)

### Mod List

GTNH 2.5.0 with updated CCC + hodgepodge (probably happens when launching just angelica+deps)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.

**Comment by The-Minecraft-Scientist** [comment]
Someone else reported this while I was writing lol
