### ISSUE TITLE
Crash when loading save recently ported from 2.5.1 to 2.6.0 Beta 1

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/Angelica#395]
### Your GTNH Discord Username

hallucinogender

### Mod Version

1.0.0 alpha 35

### Java Version

Java 17

### Graphics Card Vendor

NVidia

### Bug Report

I installed the first GTNH 2.6.0 beta version. I ported forward a save from 2.5.1 to the new instance. I had previously installed Server Utilities for chunkloading purposes. I noticed that Server Utilities is included by default in 2.6.0, so I did not install it manually

When I loaded my save for the first time in the new version, I noticed a lack of chunkloading functionality with Server Utilities. I was informed in the GTNH Discord that this functionality is disabled by default, so I re-eanbled it in the config.

When I re-launched the game after making this config, the game crashed upon loading my save again. I posted the crash report in the Discord and was informed that the crash is due to Angelica. The crash report is attached.
[crash-2024-03-23_18.16.45-client.txt](https://github.com/GTNewHorizons/Angelica/files/14733268/crash-2024-03-23_18.16.45-client.txt)

### Mod List or GTNH Pack Version

GTNH 2.6.0 Beta 1. Both this and my 2.5.1 instance also have Better Foliage 2.0.17 installed, and my 2.5.1 instance had Server Utilities as an additional mod. There are no other additional mods.

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by mitchej123** [comment]
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 14 out of bounds for object array[10]
    at java.lang.System.arraycopy(Native Method)
    at java.util.ArrayList.fastRemove(ArrayList.java:641)
    at java.util.ArrayList.remove(ArrayList.java:629)
    at crazypants.enderio.conduit.TileConduitBundle.addConnectors(TileConduitBundle.java:631)
    at crazypants.enderio.conduit.TileConduitBundle.getConnectors(TileConduitBundle.java:517)
    at crazypants.enderio.conduit.render.ConduitBundleRenderer.renderConduits(ConduitBundleRenderer.java:249)
    at crazypants.enderio.conduit.render.ConduitBundleRenderer.renderWorldBlock(ConduitBundleRenderer.java:144)
    ```
