### ISSUE TITLE
RenderGlobal.clipRenderersByFrustum Chunk build failed

### ISSUE THREAD

**Issue by SKProCH** [GTNewHorizons/Angelica#435]
### Your GTNH Discord Username

skproch

### Mod Version

angelica-1.0.0-alpha38

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

Sometimes i've just can get a aqua screen and crush with Chunk build failed, but i can't figure out why by the crashlog. This happens to me two times already. 

The reason, probably, is 
```
Cannot invoke "net.minecraft.client.multiplayer.WorldClient.func_72805_g(int, int, int)" because "net.minecraft.client.Minecraft.func_71410_x().field_71441_e" is null
```

Crashlog: https://mclo.gs/AwzYYxE
Full log: https://mclo.gs/BBtj26K

### Mod List or GTNH Pack Version

GTNH 2.6.0-beta3

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by mitchej123** [comment]
There's a lot to unpack in this log, it looks like you logged back in after a crash - which angelica doesn't (yet) clean up after itself very well for better crashes.

The first crash _appears_ unrelated to angelica.
```
Caused by: java.lang.RuntimeException: Casting data in class gregtech.common.covers.GT_Cover_LiquidMeter, data 31250
	at gregtech.api.util.GT_CoverBehaviorBase.forceCast(GT_CoverBehaviorBase.java:90) ~[GT_CoverBehaviorBase.class:?]
	at gregtech.api.util.GT_CoverBehaviorBase.getAdditionalTooltip(GT_CoverBehaviorBase.java:843) ~[GT_CoverBehaviorBase.class:?]
	at gregtech.common.covers.CoverInfo.getAdditionalTooltip(CoverInfo.java:299) ~[CoverInfo.class:?]
	at gregtech.api.metatileentity.CoverableTileEntity.getCoverTabTooltip(CoverableTileEntity.java:728) ~[CoverableTileEntity.class:?]
	at gregtech.api.metatileentity.CoverableTileEntity.lambda$addCoverTabs$5(CoverableTileEntity.java:693) ~[CoverableTileEntity.class:?]
	at com.gtnewhorizons.modularui.api.widget.Widget.buildTooltip(Widget.java:375) ~[Widget.class:?]
```

The second seems related to the recent issue I worked around/fixed in ae2 https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/508

```
java.lang.NullPointerException: Cannot invoke "appeng.client.texture.FlippableIcon.setFlip(int)" because the return value of "appeng.client.render.BlockRenderInfo.getTexture(net.minecraftforge.common.util.ForgeDirection)" is null
	at RFB-Launch//appeng.client.render.BusRenderHelper.renderBlock(BusRenderHelper.java:446) ~[BusRenderHelper.class:?]
	at RFB-Launch//appeng.parts.networking.PartCable.renderCoveredConnection(PartCable.java:656) ~[PartCable.class:?]
	at RFB-Launch//appeng.parts.networking.PartCableCovered.renderStatic(PartCableCovered.java:163) ~[PartCableCovered.class:?]
	at RFB-Launch//appeng.client.render.CableRenderHelper.renderStatic(CableRenderHelper.java:57) ~[CableRenderHelper.class:?]
```

Anything after that I've got very low confidence in given better crashes.

**Comment by mitchej123** [comment]
I would note, the GT cover crash looks potentially legit and I'd report it on the main repo.

**Comment by SKProCH** [comment]
Ok, thanks for investigation!
