### ISSUE TITLE
Crash when using intangibility ability from Fisk's Superheroes mod

### ISSUE THREAD

**Issue by Sqbri** [GTNewHorizons/Angelica#476]
### Mod Version

angelica-1.0.0-alpha42

### Java Version

Java 8

### Graphics Card Vendor

Intel iGPU

### Bug Report

When using the intangibility ability from the Fisk's Superheroes mod, you instantly crash.

To recreate install Fisk's Superheroes, join a world and wear either a "Vision" or "Martian Manhunter" suit, then use the Toggle Intangibility keybind 

### Mod List or GTNH Pack Version

![image](https://github.com/GTNewHorizons/Angelica/assets/89266562/f2b9b39e-887a-4f35-83d9-dc253b70e3f3)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by mitchej123** [comment]
Please add a crashlog

**Comment by Sqbri** [comment]
[crash-2024-05-11_23.52.19-client.txt](https://github.com/GTNewHorizons/Angelica/files/15284394/crash-2024-05-11_23.52.19-client.txt)
Here you go

**Comment by mitchej123** [comment]
It's an ARR mod with no source available, not much I can do.  I'm assuming they're trying to hook into some of the vanilla renderers and reload them , but angelica overwrites a lot of that so it's not likely to work without compat added.

```
java.lang.NullPointerException: Unexpected error
	at com.fiskmods.heroes.util.SHClientUtils.reloadRenderers(SHClientUtils.java:66)
	at com.fiskmods.heroes.common.interaction.key.KeyPressIntangibility.receive(KeyPressIntangibility.java:25)
	at com.fiskmods.heroes.common.interaction.Interaction.tryListen(Interaction.java:38)
	at com.fiskmods.heroes.common.interaction.InteractionType.interact(InteractionType.java:45)
	at com.fiskmods.heroes.common.interaction.InteractionType.interact(InteractionType.java:29)
	at com.fiskmods.heroes.common.interaction.InteractionType.interact(InteractionType.java:24)
	at com.fiskmods.heroes.common.event.ClientInputHandler.onKeyPress(ClientInputHandler.java:89)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_76_ClientInputHandler_onKeyPress_KeyInputEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
```

**Comment by mitchej123** [comment]
Fixed on their end in the next release.
