### ISSUE TITLE
PerfectSpawn Incompatibility/Transformer Error

### ISSUE THREAD

**Issue by JL2210** [GTNewHorizons/Angelica#512]
### Your GTNH Discord Username

jl2210

### Mod Version

1.0.0-alpha51

### Java Version

Other (Please Specify)

### Graphics Card Vendor

NVidia

### Bug Report

Graal java22

https://www.curseforge.com/minecraft/mc-mods/perfect-spawn

https://github.com/lumien231/Perfect-Spawn/blob/aa9f96ec93c24d3157493270ccc322aef9008d46/src/main/java/lumien/perfectspawn/Transformer/PSClassTransformer.java#L43

Relevant log excerpt:

```
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: org/spongepowered/asm/synthetic/args/Args$1
	at net.minecraft.server.management.ServerConfigurationManager.func_72372_a(ServerConfigurationManager.java:246)
	at net.minecraft.entity.EntityTracker.<init>(EntityTracker.java:56)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:99)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:62)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: org.spongepowered.asm.synthetic.args.Args$1
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 7 more
Caused by: java.lang.NullPointerException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at lumien.perfectspawn.Transformer.PSClassTransformer.transform(PSClassTransformer.java:43)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 9 more
```

Full log:
[fml-client-latest.zip](https://github.com/GTNewHorizons/Angelica/files/15497107/fml-client-latest.zip)

Installed Blightfall 3.1.1-CE, installed Angelica, updated CodeChickenCore to 1.2.1, and disabled `[✔] CoreTweaks-1.7.10-0.3.3.2-nomixin` for reproducibility. Loading in a new world causes this error. Prism Launcher 8.3 if that's relevant

### Mod List or GTNH Pack Version

```
  [✔] [1.7.10]StatusEffectHUD-client-1.27
  [✔] +unimixins-all-1.7.10-0.1.17
  [🖿] 1.7 (folder)
  [✔] angelica-1.0.0-alpha51
  [✔] AppleCore-3.2.12
  [✔] appliedenergistics2-rv3-beta-291-GTNH
  [✔] archaicfix-0.7.0
  [✔] ArchimedesShips-1.7.1
  [✔] ArmorStatusHUD-client-1.28
  [✔] Aroma1997Core-1.7.10-1.0.2.16
  [✔] AromaBackup-1.7.10-0.1.0.0
  [✔] Automagy-1.7.10-0.28.2
  [✔] betterrain-1.7.2-1.7.10_0.15
  [✔] betterrain-1.7.2-1.7.10_0.15-core
  [✔] BetterStorage-1.7.10-0.13.1.126-nosplode
  [✔] BiblioCraft[v1.11.7][MC1.7.10]
  [✔] BiblioWoods[Natura][v1.4]
  [✔] BigReactors-0.4.3A
  [✔] blightbuster-2.1.0-RC2
  [✔] blightcore-1.4.0
  [✔] blightfall-filefix-1.0.2
  [✔] BloodMagic-1.7.10-1.3.6-blight
  [✔] Botania-r1.7-208
  [✔] ChickenChunks-1.7.10-1.3.4.19-universal
  [✔] Chisel-1.7.10-1.5.7
  [✔] CodeChickenCore-1.2.1
  [✔] CoFHCore-[1.7.10]3.1.4-329
  [✔] Controlling-1.7.10-1.0.0.4
  [✔] CookingForBlockheads-1.2.16-GTNH
  [✔] CustomNPCs-1.7.10c-herohack3
  [✔] EnderStorage-1.4.13
  [✔] ExtraCells-2.5.34
  [✔] ExtraTiC-1.7.10-1.4.6
  [✔] extrautilities-1.2.12
  [✔] ExtraUtilitiesTweaks-1.0.0
  [✔] FoamFix-1.7.10-universal-1.0.2
  [✔] Forbidden Magic-1.7.10-0.575
  [✔] ForgeMultipart-1.7.10-1.2.0.345-universal
  [✔] gtnhlib-0.2.11
  [✔] HardcoreQuesting-4.4.5-blight
  [✔] HelpFixer-1.0.7
  [✔] HungerOverhaul-1.7.10-1.0.0-ConfigHack-2
  [✔] IguanaTinkerTweaks-1.7.10-2.1.6
  [✔] ImLookingAtBlood-1.7.2-1.1a
  [✔] INpureCore-[1.7.10]1.0.0B9-62
  [✔] inventorytweaks-1.58-147
  [✔] Jabba-1.2.2_1.7.10
  [✔] liteloader-1.7.10
  [✔] Lockdown-2.0.0.0
  [✔] LumySkinPatch-1.0.13
  [✔] LunatriusCore-1.7.10-1.1.2.21-universal
  [✔] Mantle-1.7.10-0.3.2b
  [✔] Metallurgy-1.7.10-4.0.9.148
  [✔] MetallurgyCore-1.7.10-4.0.5.30
  [✔] MineFactoryReloaded-[1.7.10]2.8.1-174
  [✔] MineTweaker3-1.7.10-3.0.10B
  [✔] MobiusCore-1.2.5_1.7.10
  [✔] mod_voxelMap_1.7.0b_for_1.7.10
  [✔] ModelCitizens-mc1.7.10-1.0.1
  [✔] ModTweaker2-0.9.6
  [✔] MouseTweaks-2.4.4-mc1.7.10
  [✔] natura-1.7.10-2.2.0.4
  [✔] neiaddons-1.12.14.40-mc1.7.10
  [✔] NEIPlugins-MC1.7.10-1.1.0.10-unofficial
  [✔] netherless-1.0
  [✔] NetherOres-[1.7.10]2.3.1-22
  [✔] newradicalbotany-1.1.2
  [✔] NotEnoughItems-2.4.13-GTNH
  [✔] Pam's HarvestCraft 1.7.10Lb
  [✔] PerfectSpawn-1.1
  [✔] PlayerAPI-1.7.10-1.4
  [✔] purplepanic-1.0.6
  [✔] RedstoneArsenal-[1.7.10]1.1.2-92
  [✔] RPGAdvMod-1.0.0_1.7.10
  [✔] Schematica-1.7.10-1.7.5-GenHack3
  [✔] SpiceOfLife-mc1.7.10-1.3.11
  [✔] StorageDrawers-1.7.10-1.10.9
  [✔] TabulaRasa-[1.7.10]1.0.1-3-Blight4
  [✔] TaintedPlayers-v1.1-1.7.10
  [✔] TCBotaniaExoflame-1.7.10-1.4
  [✔] tcinventoryscan-mc1.7.10-1.0.11
  [✔] tcneiadditions-a2f7577
  [✔] tcnodetracker-1.7.10-1.1.2
  [✔] TConstruct-1.7.10-1.8.8
  [🖿] TerrainControl (folder)
  [✔] terraincontrol-2.8.0-colored-lockhack-spawnfix
  [✔] Thaumcraft-1.7.10-4.2.3.5
  [✔] Thaumcraft4Tweaks-1.5.15
  [✔] thaumcraftneiplugin-1.7.10-1.7a
  [✔] thaumicenergistics-1.5.4-GTNH
  [✔] ThaumicTinkerer-blight-2.5.2-1.7.10
  [✔] ThermalDynamics-[1.7.10]1.2.1-172
  [✔] ThermalExpansion-[1.7.10]4.1.5-248
  [✔] ThermalFoundation-[1.7.10]1.2.6-118
  [✔] TiCTooltips-mc1.7.10-1.2.4
  [✔] TMechworks-1.7.10-0.2.15.106
  [✔] TooMuchLoot-1.7.10-4.0.1.B0
  [✔] Translocator-1.7.10-1.1.2.16-universal
  [✔] UBCOres-1.7.10-0.2.9.4
  [✔] UndergroundBiomesConstructs-1.7.10-0.8-beta49
  [🖿] VoxelMods (folder)
  [✔] Waila-1.5.10_1.7.10
  [✔] WailaHarvestability-mc1.7.10-1.1.6
  ```
  
  Blightfall 

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by JL2210** [comment]
Problem with PerfectSpawn, not Angelica
