### ISSUE TITLE
Game loads ok, but world crashes when turining on 

### ISSUE THREAD

**Issue by Biskupsky** [GTNewHorizons/Angelica#583]
### Mod Version

1.0.0-beta2

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

The game turns on normally, but after getting into my survival world, there is a crash reported, please help:
Time: 03.08.24 10:15
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: org/spongepowered/asm/synthetic/args/Args$1
	at net.tclproject.mysteriumlib.asm.fixes.MysteriumPatchesFixesZ.getEntityViewDistance(MysteriumPatchesFixesZ.java:63)
	at net.minecraft.server.management.ServerConfigurationManager.func_72372_a(ServerConfigurationManager.java)
	at net.minecraft.entity.EntityTracker.<init>(EntityTracker.java:56)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:99)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:62)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: org.spongepowered.asm.synthetic.args.Args$1
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more
Caused by: java.lang.NullPointerException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at invtweaks.forge.asm.ContainerTransformer.transform(ContainerTransformer.java:112)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

### Mod List or GTNH Pack Version

Time: 03.08.24 10:15
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: org/spongepowered/asm/synthetic/args/Args$1
	at net.tclproject.mysteriumlib.asm.fixes.MysteriumPatchesFixesZ.getEntityViewDistance(MysteriumPatchesFixesZ.java:63)
	at net.minecraft.server.management.ServerConfigurationManager.func_72372_a(ServerConfigurationManager.java)
	at net.minecraft.entity.EntityTracker.<init>(EntityTracker.java:56)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:99)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:62)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: org.spongepowered.asm.synthetic.args.Args$1
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more
Caused by: java.lang.NullPointerException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at invtweaks.forge.asm.ContainerTransformer.transform(ContainerTransformer.java:112)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Biskupsky** [comment]
Sorry, it happens on 5 years old main world, few weeks test worlds and also when I create new one.....
java.lang.NoClassDefFoundError: org/spongepowered/asm/synthetic/args/Args$1
	at net.tclproject.mysteriumlib.asm.fixes.MysteriumPatchesFixesZ.getEntityViewDistance(MysteriumPatchesFixesZ.java:63)
	at net.minecraft.server.management.ServerConfigurationManager.func_72372_a(ServerConfigurationManager.java)
	at net.minecraft.entity.EntityTracker.<init>(EntityTracker.java:56)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:99)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:62)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: org.spongepowered.asm.synthetic.args.Args$1
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more
Caused by: java.lang.NullPointerException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at invtweaks.forge.asm.ContainerTransformer.transform(ContainerTransformer.java:112)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 10 more

**Comment by Caedis** [comment]
`MysteriumPatchesFixesZ` burn it with fire

**Comment by mitchej123** [comment]
This doesn't seem like it's an Angelica issue, it's whatever is using mysterium to patch stuff... and you didn't even provide a modlist.  Plus if you're on java 21 like yous ay, the NPE would be more detailed

**Comment by JL2210** [comment]
I think this error happens when lwjgl3ify launch args are above liteloader if you're using Prism/MMC and LiteLoader

**Comment by Biskupsky** [comment]
Its solved, Inventory Tweaks makes that shit - I would never guess till I deleted mods one by one XD
