### ISSUE TITLE
MCHELI crash

### ISSUE THREAD

**Issue by Biskupsky** [GTNewHorizons/Angelica#584]
### Mod Version

1.0.0-beta2

### Java Version

Java 21

### Graphics Card Vendor

NVidia

### Bug Report

Mcheli missiles (TV, normal ones) very often crash when reaching target (I use 20 chunks load, 32 chunks max visible) Report:
Description: Unexpected error

java.lang.RuntimeException: Chunk build failed
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.handleFailures(ChunkBuilder.java:219)
	at me.jellysquid.mods.sodium.client.render.chunk.ChunkRenderManager.updateChunks(ChunkRenderManager.java:590)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:246)
	at net.minecraft.client.renderer.RenderGlobal.func_72729_a(RenderGlobal.java:4188)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1181)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:215)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:409)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1887)
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:211)
	... 2 more
Caused by: java.lang.NullPointerException
	at com.jaquadro.minecraft.gardencontainers.block.BlockWindowBox.func_149719_a(BlockWindowBox.java:182)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:249)
	at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderModel(BlockRenderer.java:98)
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performMainBuild(ChunkRenderRebuildTask.java:281)
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.lambda$performBuild$0(ChunkRenderRebuildTask.java:208)
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask$$Lambda$385/257616310.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618)
	at com.gtnewhorizons.angelica.rendering.AngelicaRenderQueue.processTasks(AngelicaRenderQueue.java:33)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:4106)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

### Mod List or GTNH Pack Version

![sdfg](https://github.com/user-attachments/assets/84fd8344-dc4d-40cf-8a0a-e9bb1f9ac39d)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by mitchej123** [comment]
Looks like Garden Stuff isn't thread safe....

**Comment by Biskupsky** [comment]
I must admit that its funny, that mod for better looking pots could be thread unsafe XD thanks for help

**Comment by MalTeeez** [comment]
Tested on latest with GardenCollection and could not reproduce anymore - feel free to reopen if you still have this issue.
