### ISSUE TITLE
rare SSR+++ crash with redlogic

### ISSUE THREAD

**Issue by Yoghurt4C** [GTNewHorizons/Angelica#675]
### Mod Version

alpha10

### Java Version

Java 21

### Graphics Card Vendor

AMD/ATI

### Shaders

No: Go ahead and create an issue

### MCPF or other features disabled by default

No: Go ahead and create an issue

### Bug Report

```js
FATAL ERROR in native method: Thread[#122,Chunk Render Task Executor #1,3,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.GL11C.glBindTexture(Native Method)
	at org.lwjgl.opengl.GL11.glBindTexture(GL11.java:854)
	at org.lwjglx.opengl.GL11.glBindTexture(GL11.java:560)
	at com.gtnewhorizons.angelica.glsm.GLStateManager.glBindTexture(GLStateManager.java:820)
	at net.minecraft.client.renderer.texture.TextureUtil.func_94277_a(TextureUtil.java:342)
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:48)
	at mods.immibis.redlogic.gates.GateStaticRenderer.renderActualGate(GateStaticRenderer.java:44)
	at mods.immibis.redlogic.gates.GateTile.renderPartContainer(GateTile.java:560)
	at mods.immibis.core.multipart.ClientProxy.renderMultiparts(ClientProxy.java:32)
	at mods.immibis.core.multipart.MultipartSystem.renderMultiparts(MultipartSystem.java:448)
	at mods.immibis.core.multipart.MCTHooks.client_postRenderBlockInWorld(MCTHooks.java:82)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:296)
	at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderModel(BlockRenderer.java:103)
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:161)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:409)
	at java.lang.Thread.runWith(java.base@21.0.4/Thread.java:1596)
	at java.lang.Thread.run(java.base@21.0.4/Thread.java:1583)```

### Mod List or GTNH Pack Version

angelica-1.0.0-beta10.rar
immibis-core-59.1.4.tar.gz
redlogic-59.1.13.7z

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Yoghurt4C** [comment]
note that this only happens sometimes when a redlogic game/alloy wire ticks and seemingly goes away when chunk multidraw is disabled

**Comment by MalTeeez** [comment]
Cant reproduce on latest, is probably fixed. If it still happens free to comment here, and if possible provide a screenshot of your setup that caused it.
