### ISSUE TITLE
Minecraft freezes in loading screen after leaving world

### ISSUE THREAD

**Issue by Marvun** [GTNewHorizons/Angelica#73]
### Your GTNH Discord Username

ichheissemarvin

### Mod Version

1.0.0-alpha7

### Java Version

Java 19

### Bug Report

When i try to leave my world, i get stuck in the loading screen and in my log i have a never ending error spam.
It all starts with:
```
[13:10:13] [Client thread/ERROR] [FML]: Exception caught during firing event cpw.mods.fml.common.gameevent.TickEvent$ClientTickEvent@1fb853ab:
java.lang.NullPointerException: Cannot invoke "me.jellysquid.mods.sodium.client.render.chunk.ChunkRenderManager.scheduleRebuild(int, int, int, boolean)" because "this.chunkRenderManager" is null
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.scheduleRebuildForChunk(SodiumWorldRenderer.java:447) ~[SodiumWorldRenderer.class:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.scheduleRebuildForChunks(SodiumWorldRenderer.java:437) ~[SodiumWorldRenderer.class:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.scheduleRebuildForBlockArea(SodiumWorldRenderer.java:427) ~[SodiumWorldRenderer.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_72725_b(RenderGlobal.java:4697) ~[bma.class:?]
	at com.sinthoras.hydroenergy.client.light.HELightManager.markChunkForRerender(HELightManager.java:183) ~[HELightManager.class:?]
	at com.sinthoras.hydroenergy.client.light.HELightManager.triggerLightingUpdate(HELightManager.java:145) ~[HELightManager.class:?]
	at com.sinthoras.hydroenergy.client.light.HELightManager.onTick(HELightManager.java:110) ~[HELightManager.class:?]
	at com.sinthoras.hydroenergy.hooks.HEHooksFML.onEvent(HEHooksFML.java:54) ~[HEHooksFML.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1678_HEHooksFML_onEvent_ClientTickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330) [FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2064) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3610) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:165) [lwjgl3ify-1.5.7-forgePatches.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:29) [lwjgl3ify-1.5.7-forgePatches.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```
This is the full log until i killed the process:
[log.txt](https://github.com/GTNewHorizons/Angelica/files/13778583/log.txt)

The problem is that i can only reproduce this with the specific world. So it probably has to do with something that is in the world, but i can't tell what.
If i can provide more information somehow, let me know.

### Mod List or GTNH Pack Version

GTNH 2.5.2 with the updated mods for angelica

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.

**Comment by Caedis** [comment]
Do you happen to have anything hydroenergy related, say around build height?

**Comment by Marvun** [comment]
Actually yes, since this is my test world, I was testing around with it.

**Comment by Caedis** [comment]
Its a known issue, we can keep this one open to keep track of it

**Comment by bombcar** [comment]
As a workaround, if you move so the dam is out of render distance (chunk can even be loaded, just has to be not rendered) it unloads correctly and you can exit.

**Comment by Caedis** [comment]
should be able to edit your render distance in `options.txt`

**Comment by dvdmandt** [comment]
I can confirm that this is still an issue with GTNH 2.6.0 (Angelica alpha-40)

[crash-2024-04-29_20.29.30-client.txt](https://github.com/GTNewHorizons/Angelica/files/15153478/crash-2024-04-29_20.29.30-client.txt)
[crash-2024-04-29_20.29.27-client.txt](https://github.com/GTNewHorizons/Angelica/files/15153479/crash-2024-04-29_20.29.27-client.txt)

**Comment by Caedis** [comment]
Fixed with https://github.com/GTNewHorizons/HydroEnergy/releases/tag/1.3.0
