### ISSUE TITLE
Angelica shaders isn't working on Mac

### ISSUE THREAD

**Issue by dandelion711** [GTNewHorizons/Angelica#738]
### Your GTNH Discord Username

dandelion91

### Mod Version

beta20

### Bug Report

I have enabled Iris in the Angelica config, but when I enable shaders, it takes a moment to load, but no shaders are applied, and, practically, nothing changes whatsoever
I'm running GTNH on an Apple silicon Mac 

### Java Version

Java 21

### Graphics Card Vendor

Other (Please Specify)

### Shaders

Yes: Please put relevant information about shaderpack in the report(what shaderpack, any special settings of note, etc)

### MCPF or other features disabled by default

No: Go ahead and create an issue

### Mod List or GTNH Pack Version

GTNH 2.6.1

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)

**Comment by mitchej123** [comment]
Not sure what you expect us to do without a log of some sort..  I've tested shaders on osx

**Comment by Cleptomania** [comment]
Yeah we need logs to do anything. If the shaders don't end up applying it's because they failed to compile. What shader pack are you trying to use?

**Comment by dandelion711** [comment]
`[00:04:05] [Client thread/ERROR] [AngelicaShaders]: Failed to create shader rendering pipeline, disabling shaders!
java.lang.RuntimeException: Shader compilation failed!
	at RFB-Launch//net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:313) ~[CompositeRenderer.class:?]
	at RFB-Launch//net.coderbot.iris.postprocess.CompositeRenderer.<init>(CompositeRenderer.java:98) ~[CompositeRenderer.class:?]
	at RFB-Launch//net.coderbot.iris.pipeline.DeferredWorldRenderingPipeline.<init>(DeferredWorldRenderingPipeline.java:245) ~[DeferredWorldRenderingPipeline.class:?]
	at RFB-Launch//net.coderbot.iris.Iris.createPipeline(Iris.java:565) ~[Iris.class:?]
	at RFB-Launch//net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:37) ~[PipelineManager.class:?]
	at RFB-Launch//net.coderbot.iris.Iris.reload(Iris.java:506) ~[Iris.class:?]
	at RFB-Launch//net.coderbot.iris.apiimpl.IrisApiV0ConfigImpl.setShadersEnabledAndApply(IrisApiV0ConfigImpl.java:28) ~[IrisApiV0ConfigImpl.class:?]
	at RFB-Launch//net.coderbot.iris.gui.screen.ShaderPackScreen.applyChanges(ShaderPackScreen.java:405) ~[ShaderPackScreen.class:?]
	at RFB-Launch//net.coderbot.iris.gui.screen.ShaderPackScreen.lambda$initGui$4(ShaderPackScreen.java:227) ~[ShaderPackScreen.class:?]
	at RFB-Launch//net.coderbot.iris.gui.element.widget.IrisButton.onPress(IrisButton.java:18) [IrisButton.class:?]
	at RFB-Launch//net.coderbot.iris.gui.screen.ShaderPackScreen.func_146284_a(ShaderPackScreen.java:314) [ShaderPackScreen.class:?]
	at RFB-Launch//net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225) [bdw.class:?]
	at RFB-Launch//net.coderbot.iris.gui.screen.ShaderPackScreen.func_73864_a(ShaderPackScreen.java:286) [ShaderPackScreen.class:?]
	at RFB-Launch//net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296) [bdw.class:?]
	at RFB-Launch//net.coderbot.iris.gui.element.IrisGuiSlot.func_148128_a(IrisGuiSlot.java:114) [IrisGuiSlot.class:?]
	at RFB-Launch//net.coderbot.iris.gui.screen.ShaderPackScreen.func_73863_a(ShaderPackScreen.java:110) [ShaderPackScreen.class:?]
	at RFB-Launch//net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061) [blt.class:?]
	at RFB-Launch//net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) [bao.class:?]
	at RFB-Launch//net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:6110) [bao.class:?]
	at RFB-Launch//net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at RFB-System//net.minecraft.launchwrapper.Launch.rfb$realLaunch(Launch.java:250) [Launch.class:?]
	at RFB-System//net.minecraft.launchwrapper.Launch.launch(Launch.java:35) [Launch.class:?]
	at RFB-System//net.minecraft.launchwrapper.Launch.main(Launch.java:60) [Launch.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at com.gtnewhorizons.retrofuturabootstrap.Main.main(Main.java:219) [lwjgl3ify-2.0.9-forgePatches.jar:?]
	at RFB-System//org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at RFB-System//org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at RFB-System//org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Failed to compile VERTEX shader for program deferred1.vsh
	at RFB-Launch//net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:94) ~[ProgramBuilder.class:?]
	at RFB-Launch//net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:39) ~[ProgramBuilder.class:?]
	at RFB-Launch//net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:309) ~[CompositeRenderer.class:?]
	... 30 more
Caused by: java.lang.RuntimeException: Shader compilation failed, see log for details
	at RFB-Launch//net.coderbot.iris.gl.shader.GlShader.createShader(GlShader.java:49) ~[GlShader.class:?]
	at RFB-Launch//net.coderbot.iris.gl.shader.GlShader.<init>(GlShader.java:25) ~[GlShader.class:?]
	at RFB-Launch//net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:92) ~[ProgramBuilder.class:?]
	at RFB-Launch//net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:39) ~[ProgramBuilder.class:?]
	at RFB-Launch//net.coderbot.iris.postprocess.CompositeRenderer.createProgram(CompositeRenderer.java:309) ~[CompositeRenderer.class:?]
	... 30 more
[00:04:05] [Client thread/INFO] [ChunkBuilder]: Stopping worker threads
[00:04:05] [Client thread/INFO] [ChunkBuilder]: Started 2 worker threads
`

here's what I've found in the Minecraft log as soon as I try to load the shaders. I'm using complementaryReimagined shaders 5.3 (tried complementaryShaders 4.7.2 as well)

**Comment by Cleptomania** [comment]
Can you upload the entire log file?

**Comment by dandelion711** [comment]
https://mclo.gs/wy9LKO0

**Comment by Cleptomania** [comment]
Ahh yeah, you're just not going to be able to use Complementary 5.3 on Mac OS unfortunately. Complementary 5.3 uses stuff that is only available on OpenGL 3.0+, and Mac OS will only provide OpenGL 2.1. This is something that might eventually get fixed in Angelica once we emulate compatibility profile, but is definitely not going to happen anytime soon.

Other versions of Complementary might have the same problems, or other shader packs, I'm not sure, it's up to the shader pack. This would also break on Optifine. Unfortunately Mac OS is just going to have less support for shaderpacks that use anything above GLSL 120, nothing we can do about it really.

**Comment by dandelion711** [comment]
Thank you for the insight! I installed BSL 8.4 and it actually works as intended. Also tried a few other shader packs but to no avail

**Comment by Cleptomania** [comment]
If you happen to have a list of ones that don't work for you, you could post it here. At some point I will probably go through a bunch of them and figure out what ones do/don't work on Mac OS.

When it comes to BSL and Complementary, BSL 8.3 is the only one that entirely doesn't work with Angelica, it had a bug with it that was fixed in 8.4, and didn't exist in 8.2. Every other version of BSL and Complementary largely should work with Angelica, but I haven't tested them on Mac OS, so there could be varying levels of success with each specific version there, or even could be some specific shader settings that trigger the incompatibility.

**Comment by dandelion711** [comment]
I’ve done some testing with various shaders (potato shaders, shrimple, super duper vanilla, wisdom shaders, and some others) but none of them worked, i also tried different versions of complementary, but there were only two outcomes: either Minecraft would crash, or simple not enable. Only BSL 8.4 would work fine
